import { StyleSheet } from 'react-native';

// Sistema de cores: base neutra e quente, verde-pinho para ações e
// terracota reservado ao destaque da próxima dose.
export const cores = {
  fundo: '#F6F4EF',
  branco: '#FFFFFF',
  texto: '#231F1B',
  mutado: '#726B60',
  borda: '#E4DFD3',
  verde: '#2C5A4C',
  verdeClaro: '#E7EDE6',
  destaque: '#B5652E',
  destaqueClaro: '#F4E4D8',
  ambar: '#9C6B2E',
  ambarClaro: '#F3E6D2',
  vermelho: '#A63F2E',
  vermelhoClaro: '#F5E1DC',
};

export const estilos = StyleSheet.create({
  botao: { minHeight: 48, borderRadius: 12, paddingHorizontal: 17, alignItems: 'center', justifyContent: 'center', marginTop: 10 },
  botaoPrimario: { backgroundColor: cores.verde },
  botaoSuave: { backgroundColor: cores.verdeClaro },
  botaoPerigo: { backgroundColor: cores.vermelhoClaro, borderWidth: 1, borderColor: '#DDB2A8' },
  botaoTexto: { backgroundColor: 'transparent', paddingHorizontal: 5 },
  textoBotao: { color: cores.branco, fontSize: 16, fontWeight: '600' },
  textoBotaoSuave: { color: cores.texto },
  textoBotaoTexto: { color: cores.destaque, textDecorationLine: 'underline' },
  pressionado: { opacity: 0.7 },
  desativado: { opacity: 0.45 },

  campo: { marginTop: 18 },
  label: { color: cores.texto, fontSize: 15, fontWeight: '600', marginBottom: 7 },
  input: { minHeight: 52, borderWidth: 1, borderColor: cores.borda, borderRadius: 12, backgroundColor: cores.branco, paddingHorizontal: 14, color: cores.texto, fontSize: 17 },
  erro: { color: cores.vermelho, fontSize: 14, marginTop: 6 },
  escolhas: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  selecionado: { borderWidth: 2, borderColor: cores.verde },

  horarioLinha: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  horarioIndice: { width: 34, height: 34, borderRadius: 17, backgroundColor: cores.verdeClaro, alignItems: 'center', justifyContent: 'center' },
  horarioNumero: { color: cores.verde, fontSize: 12, fontWeight: '600' },
  horarioConteudo: { flex: 1 },
  horarioBotao: { minHeight: 60, borderWidth: 1, borderColor: cores.borda, borderRadius: 12, backgroundColor: cores.branco, paddingHorizontal: 15, paddingVertical: 9, justifyContent: 'center' },
  horarioValor: { color: cores.texto, fontSize: 22, fontWeight: '700', fontVariant: ['tabular-nums'], letterSpacing: 0.5 },
  horarioDica: { color: cores.mutado, fontSize: 12, marginTop: 2 },
  horarioRemover: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' },
  horarioRemoverTexto: { color: cores.vermelho, fontSize: 28, fontWeight: '300' },

  pickerBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(35,31,27,0.32)' },
  pickerFolha: { backgroundColor: cores.fundo, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 22, paddingBottom: 28 },
  pickerAcao: { minWidth: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  pickerCancelar: { color: cores.verde, fontSize: 14, fontWeight: '600', padding: 8 },
  modalFechar: { minWidth: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center' },

  cartao: { backgroundColor: cores.branco, borderRadius: 14, padding: 17, marginBottom: 12, borderWidth: 1, borderColor: cores.borda },
  linhaEntre: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 },
  flexivel: { flex: 1 },
  titulo: { color: cores.texto, fontSize: 24, lineHeight: 30, fontWeight: '700', marginTop: 10, marginBottom: 4 },
  lead: { color: cores.mutado, fontSize: 16, lineHeight: 23, marginBottom: 18 },
  nome: { color: cores.texto, fontSize: 17, fontWeight: '600' },
  secundario: { color: cores.mutado, fontSize: 14, lineHeight: 20 },
  ajuda: { color: cores.mutado, fontSize: 15, lineHeight: 22, marginVertical: 14 },
  ajudaCampo: { color: cores.mutado, fontSize: 14, lineHeight: 20, marginTop: -3, marginBottom: 12 },
  secaoTitulo: { color: cores.texto, fontSize: 17, fontWeight: '700', marginTop: 22, marginBottom: 4 },
  vazio: { backgroundColor: cores.branco, borderRadius: 14, padding: 18, borderWidth: 1, borderColor: cores.borda, marginTop: 10, marginBottom: 16 },
  seta: { color: cores.mutado, fontSize: 26, lineHeight: 24, fontWeight: '300' },

  proximaDose: { flexDirection: 'row', alignItems: 'center', backgroundColor: cores.destaqueClaro, borderRadius: 14, padding: 16, marginTop: 6, marginBottom: 4, gap: 14 },
  proximaDoseHorario: { color: cores.destaque, fontSize: 20, fontWeight: '700', fontVariant: ['tabular-nums'] },
  proximaDoseLegenda: { color: cores.destaque, fontSize: 12, marginTop: 2 },
  proximaDoseNome: { color: cores.texto, fontSize: 18, fontWeight: '600' },
  proximaDoseTexto: { color: cores.mutado, fontSize: 14, marginTop: 2 },
  linhaLista: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: cores.borda, gap: 14 },
  linhaListaUltima: { borderBottomWidth: 0 },
  horaLista: { width: 52, color: cores.texto, fontSize: 15, fontWeight: '600', fontVariant: ['tabular-nums'] },
  horaListaConcluida: { color: cores.mutado, fontWeight: '400' },
  conteudoLista: { flex: 1 },
  nomeListaConcluido: { color: cores.mutado, textDecorationLine: 'line-through' },
  acoesLista: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  compromisso: { borderLeftWidth: 3, borderLeftColor: cores.destaque, paddingLeft: 14, paddingVertical: 2, marginBottom: 14 },

  rotinaItem: { paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: cores.borda },
  rotinaLinha: { flexDirection: 'row', alignItems: 'flex-start', gap: 14 },
  horarioLista: { width: 64, color: cores.texto, fontSize: 18, fontWeight: '600', fontVariant: ['tabular-nums'], paddingTop: 1 },
  rotinaConteudo: { flex: 1, minWidth: 0 },
  rotinaAcoes: { flexDirection: 'column', alignItems: 'stretch', gap: 4, marginTop: 12 },
  listaCabecalho: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 2, marginBottom: 6 },
  cabecalhoResumo: { color: cores.mutado, fontSize: 14, fontWeight: '600', paddingBottom: 12 },

  medicamentoItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: cores.borda, gap: 12 },
  statusMarcador: { width: 4, alignSelf: 'stretch', borderRadius: 2, backgroundColor: cores.verde },
  statusMarcadorPausado: { backgroundColor: cores.ambar },
  horariosLista: { color: cores.mutado, fontSize: 14, marginTop: 3, fontVariant: ['tabular-nums'] },
  observacaoLista: { color: cores.mutado, fontSize: 14, lineHeight: 20, marginTop: 6 },

  historicoItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: cores.borda, gap: 12 },
  historicoFiltros: { backgroundColor: cores.branco, borderRadius: 14, padding: 14, marginBottom: 16, borderWidth: 1, borderColor: cores.borda },
  historicoPeriodoLabel: { marginTop: 16 },
  historicoMarcador: { width: 9, height: 9, borderRadius: 5 },
  historicoMarcadorTomado: { backgroundColor: cores.verde },
  historicoMarcadorAdiado: { backgroundColor: cores.ambar },
  historicoMarcadorEsquecido: { backgroundColor: cores.vermelho },
  historicoMarcadorPendente: { backgroundColor: cores.mutado },
  statusTexto: { fontSize: 13, fontWeight: '600' },
  statusTomado: { color: cores.verde },
  statusAdiado: { color: cores.ambar },
  statusEsquecido: { color: cores.vermelho },
  statusPendente: { color: cores.mutado },

  boasVindasMarca: { color: cores.verde, fontWeight: '600', fontSize: 16, marginBottom: 32 },
  boasVindasTitulo: { color: cores.texto, fontSize: 30, lineHeight: 37, fontWeight: '700' },
  boasVindasTexto: { color: cores.mutado, fontSize: 17, lineHeight: 25, marginTop: 14, marginBottom: 20 },
  avisoClinico: { backgroundColor: cores.verdeClaro, borderRadius: 12, padding: 16, marginVertical: 16, borderLeftWidth: 3, borderLeftColor: cores.verde },
});
