import { StyleSheet } from 'react-native';

export const espacamentos = { xxs: 4, xs: 8, sm: 12, md: 16, lg: 20, xl: 24, xxl: 32 } as const;
export const raios = { pequeno: 8, medio: 10, grande: 12 } as const;
export const tamanhos = { toqueMinimo: 48, conteudoMaximo: 720, navegacaoBase: 62 } as const;
export const tipografia = {
  titulo: { fontSize: 28, lineHeight: 34, fontWeight: '700' as const },
  secao: { fontSize: 17, lineHeight: 23, fontWeight: '700' as const },
  corpo: { fontSize: 16, lineHeight: 23 },
  secundario: { fontSize: 14, lineHeight: 20 },
} as const;

// Sistema de cores: base neutra e quente, verde-pinho para ações e
// terracota reservado ao destaque da próxima dose.
export const cores = {
  fundo: '#F6F4EF',
  branco: '#FFFFFF',
  texto: '#231F1B',
  mutado: '#675E52',
  borda: '#E4DFD3',
  verde: '#2C5A4C',
  verdeClaro: '#E7EDE6',
  destaque: '#905026',
  destaqueClaro: '#F4E4D8',
  ambar: '#865B25',
  ambarClaro: '#F3E6D2',
  vermelho: '#A63F2E',
  vermelhoClaro: '#F5E1DC',
};

export const estilos = StyleSheet.create({
  tela: { flex: 1, backgroundColor: cores.fundo },
  conteudo: { width: '100%', maxWidth: tamanhos.conteudoMaximo, alignSelf: 'center', paddingHorizontal: espacamentos.lg },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(35,31,27,0.32)' },
  modalFolha: { maxHeight: '88%', backgroundColor: cores.fundo, borderTopLeftRadius: raios.grande, borderTopRightRadius: raios.grande, padding: espacamentos.lg, paddingBottom: espacamentos.xxl },
  campoMultilinha: { minHeight: 96, paddingTop: 14 },
  botaoConteudo: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', flexWrap: 'wrap', flexShrink: 1, gap: espacamentos.xs },
  acaoSecundaria: { color: cores.verde, fontSize: 15, fontWeight: '600' },
  divisor: { borderBottomWidth: 1, borderBottomColor: cores.borda },

  navegacao: { backgroundColor: cores.branco, borderTopWidth: 1, borderTopColor: cores.borda, flexDirection: 'row', paddingHorizontal: espacamentos.xs },
  itemNavegacao: { flex: 1, alignItems: 'center', minHeight: tamanhos.navegacaoBase, justifyContent: 'center', paddingHorizontal: espacamentos.xxs, paddingTop: espacamentos.xs, paddingBottom: espacamentos.xs },
  rotuloNavegacao: { flexShrink: 1, color: cores.mutado, fontSize: 13, lineHeight: 17, fontWeight: '400', marginTop: 3, textAlign: 'center' },
  rotuloNavegacaoSelecionado: { color: cores.verde, fontWeight: '700' },
  indicadorNavegacao: { width: 22, height: 2, borderRadius: 1, marginTop: 3, backgroundColor: 'transparent' },
  indicadorNavegacaoSelecionado: { backgroundColor: cores.verde },

  botao: { minHeight: tamanhos.toqueMinimo, borderRadius: raios.grande, paddingHorizontal: 17, alignItems: 'center', justifyContent: 'center', marginTop: espacamentos.sm },
  botaoPrimario: { backgroundColor: cores.verde },
  botaoSuave: { backgroundColor: cores.verdeClaro },
  botaoPerigo: { backgroundColor: cores.vermelhoClaro, borderWidth: 1, borderColor: '#DDB2A8' },
  botaoTexto: { backgroundColor: 'transparent', paddingHorizontal: espacamentos.xxs },
  textoBotao: { flexShrink: 1, color: cores.branco, fontSize: tipografia.corpo.fontSize, lineHeight: tipografia.corpo.lineHeight, fontWeight: '600', textAlign: 'center' },
  textoBotaoSuave: { color: cores.texto },
  textoBotaoTexto: { color: cores.destaque, textDecorationLine: 'underline' },
  pressionado: { opacity: 0.7 },
  desativado: { opacity: 0.45 },

  campo: { marginTop: espacamentos.lg },
  label: { color: cores.texto, fontSize: 15, fontWeight: '600', marginBottom: espacamentos.xs },
  input: { minHeight: 52, borderWidth: 1, borderColor: cores.borda, borderRadius: raios.grande, backgroundColor: cores.branco, paddingHorizontal: 14, color: cores.texto, fontSize: tipografia.secao.fontSize },
  erro: { color: cores.vermelho, ...tipografia.secundario, marginTop: espacamentos.xs },
  escolhas: { flexDirection: 'row', flexWrap: 'wrap', gap: espacamentos.xs },
  frequenciaOpcoes: { alignItems: 'stretch', marginBottom: espacamentos.sm },
  selecionado: { borderWidth: 2, borderColor: cores.verde },

  horarioLinha: { flexDirection: 'row', alignItems: 'center', gap: espacamentos.sm, marginBottom: espacamentos.sm },
  horarioIndice: { width: 34, height: 34, borderRadius: 17, backgroundColor: cores.verdeClaro, alignItems: 'center', justifyContent: 'center' },
  horarioNumero: { color: cores.verde, fontSize: 12, fontWeight: '600' },
  horarioConteudo: { flex: 1 },
  horarioBotao: { minHeight: 60, borderWidth: 1, borderColor: cores.borda, borderRadius: raios.grande, backgroundColor: cores.branco, paddingHorizontal: 15, paddingVertical: 9, justifyContent: 'center' },
  horarioValor: { color: cores.texto, fontSize: 22, fontWeight: '700', fontVariant: ['tabular-nums'], letterSpacing: 0.5 },
  horarioDica: { color: cores.mutado, fontSize: 12, marginTop: 2 },
  horarioRemover: { width: tamanhos.toqueMinimo, height: tamanhos.toqueMinimo, alignItems: 'center', justifyContent: 'center' },
  horarioRemoverTexto: { color: cores.vermelho, fontSize: 28, fontWeight: '300' },

  pickerBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(35,31,27,0.32)' },
  pickerFolha: { backgroundColor: cores.fundo, borderTopLeftRadius: raios.grande, borderTopRightRadius: raios.grande, padding: espacamentos.lg, paddingBottom: espacamentos.xxl },
  pickerAcao: { minWidth: tamanhos.toqueMinimo, minHeight: tamanhos.toqueMinimo, alignItems: 'center', justifyContent: 'center' },
  pickerCancelar: { color: cores.verde, ...tipografia.secundario, fontWeight: '600', padding: espacamentos.xs },
  modalFechar: { minWidth: tamanhos.toqueMinimo, minHeight: tamanhos.toqueMinimo, alignItems: 'center', justifyContent: 'center' },

  cartao: { backgroundColor: cores.branco, borderRadius: raios.grande, padding: 17, marginBottom: espacamentos.sm, borderWidth: 1, borderColor: cores.borda },
  linhaEntre: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: espacamentos.sm },
  flexivel: { flex: 1 },
  titulo: { color: cores.texto, ...tipografia.titulo, marginTop: espacamentos.sm, marginBottom: espacamentos.xxs },
  dataHoje: { color: cores.mutado, ...tipografia.corpo, marginBottom: espacamentos.lg },
  lead: { color: cores.mutado, ...tipografia.corpo, marginBottom: espacamentos.lg },
  nome: { color: cores.texto, fontSize: tipografia.secao.fontSize, fontWeight: '600' },
  secundario: { color: cores.mutado, ...tipografia.secundario },
  ajuda: { color: cores.mutado, fontSize: 15, lineHeight: 22, marginVertical: 14 },
  ajudaCampo: { color: cores.mutado, ...tipografia.secundario, marginTop: -3, marginBottom: espacamentos.sm },
  secaoTitulo: { color: cores.texto, ...tipografia.secao, marginTop: 22, marginBottom: espacamentos.xxs },
  vazio: { backgroundColor: cores.branco, borderRadius: raios.grande, padding: 18, borderWidth: 1, borderColor: cores.borda, marginTop: espacamentos.sm, marginBottom: espacamentos.md },
  seta: { color: cores.mutado, fontSize: 26, lineHeight: 24, fontWeight: '300' },

  avisoDesfazer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: espacamentos.xs, paddingVertical: espacamentos.xs, borderBottomWidth: 1, borderBottomColor: cores.borda },
  proximaDose: { backgroundColor: cores.destaqueClaro, borderRadius: raios.grande, padding: espacamentos.md, marginBottom: espacamentos.xxs },
  proximaDoseCabecalho: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: espacamentos.xs },
  proximaDoseIdentificacao: { flexDirection: 'row', alignItems: 'center', gap: espacamentos.md, marginTop: espacamentos.sm },
  proximaDoseHorario: { color: cores.destaque, fontSize: 20, fontWeight: '700', fontVariant: ['tabular-nums'] },
  proximaDoseLegenda: { color: cores.destaque, ...tipografia.secundario, fontWeight: '700' },
  proximaDoseNome: { color: cores.texto, fontSize: 18, fontWeight: '600' },
  proximaDoseTexto: { color: cores.mutado, fontSize: 14, marginTop: 2 },
  linhaLista: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: cores.borda, gap: 14 },
  linhaListaUltima: { borderBottomWidth: 0 },
  horaLista: { width: 52, color: cores.texto, fontSize: 15, fontWeight: '600', fontVariant: ['tabular-nums'] },
  horaListaConcluida: { color: cores.mutado, fontWeight: '400' },
  conteudoLista: { flex: 1 },
  nomeListaConcluido: { color: cores.mutado, textDecorationLine: 'line-through' },
  acoesLista: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  compromisso: { flexDirection: 'row', alignItems: 'flex-start', gap: espacamentos.sm, paddingVertical: espacamentos.sm, borderBottomWidth: 1, borderBottomColor: cores.borda },
  linhaConfiguracao: { flexDirection: 'row', alignItems: 'center', minHeight: tamanhos.toqueMinimo, gap: espacamentos.sm, paddingVertical: espacamentos.sm, borderBottomWidth: 1, borderBottomColor: cores.borda },
  textoConfiguracao: { flex: 1, minWidth: 0 },

  rotinaItem: { paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: cores.borda },
  rotinaLinha: { flexDirection: 'row', alignItems: 'flex-start', gap: 14 },
  horarioLista: { width: 64, color: cores.texto, fontSize: 18, fontWeight: '600', fontVariant: ['tabular-nums'], paddingTop: 1 },
  rotinaConteudo: { flex: 1, minWidth: 0 },
  rotinaAcoes: { flexDirection: 'row', alignItems: 'flex-start', flexWrap: 'wrap', gap: espacamentos.xs, minHeight: tamanhos.toqueMinimo, marginTop: espacamentos.sm },
  listaCabecalho: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 2, marginBottom: 6 },
  cabecalhoResumo: { color: cores.mutado, fontSize: 14, fontWeight: '600', paddingBottom: 12 },

  medicamentoItem: { flexDirection: 'row', alignItems: 'center', minHeight: tamanhos.toqueMinimo, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: cores.borda, gap: 12 },
  medicamentoSituacao: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: espacamentos.xxs, marginTop: espacamentos.xs },
  medicamentoSituacaoTexto: { ...tipografia.secundario, fontWeight: '600' },
  registrosRecentes: { marginTop: espacamentos.xl },
  registroRecente: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: espacamentos.xs, paddingVertical: espacamentos.sm, borderBottomWidth: 1, borderBottomColor: cores.borda },
  statusMarcador: { width: 4, alignSelf: 'stretch', borderRadius: 2, backgroundColor: cores.verde },
  statusMarcadorPausado: { backgroundColor: cores.ambar },
  horariosLista: { color: cores.mutado, fontSize: 14, marginTop: 3, fontVariant: ['tabular-nums'] },
  observacaoLista: { color: cores.mutado, fontSize: 14, lineHeight: 20, marginTop: 6 },

  historicoGrupoTitulo: { color: cores.mutado, ...tipografia.secundario, fontWeight: '700', marginTop: espacamentos.lg, marginBottom: espacamentos.xxs },
  historicoItem: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: cores.borda, gap: espacamentos.sm },
  historicoHorario: { color: cores.texto, fontSize: 15, fontWeight: '600', fontVariant: ['tabular-nums'], paddingTop: 1 },
  historicoFiltros: { backgroundColor: cores.branco, borderRadius: raios.grande, padding: 14, marginBottom: espacamentos.md, borderWidth: 1, borderColor: cores.borda },
  historicoPeriodoLabel: { marginTop: 16 },
  historicoMarcador: { width: 9, height: 9, borderRadius: 5 },
  historicoMarcadorTomado: { backgroundColor: cores.verde },
  historicoMarcadorAdiado: { backgroundColor: cores.ambar },
  historicoMarcadorEsquecido: { backgroundColor: cores.vermelho },
  historicoMarcadorPendente: { backgroundColor: cores.mutado },
  statusTexto: { fontSize: 13, fontWeight: '600' },
  statusTomado: { color: cores.verde },
  statusAdiado: { color: cores.ambar },
  statusEsquecido: { color: cores.vermelho },
  statusPendente: { color: cores.mutado },
  estadoRegistro: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: espacamentos.xxs, marginTop: espacamentos.xs },
  estadoRegistroCompacto: { marginTop: 0 },
  estadoRegistroTexto: { ...tipografia.secundario, fontWeight: '600' },
  estadoRegistroTextoCompacto: { fontSize: 13, lineHeight: 18 },

  boasVindasMarca: { color: cores.verde, fontWeight: '600', fontSize: 16, marginBottom: 32 },
  boasVindasTitulo: { color: cores.texto, fontSize: 30, lineHeight: 37, fontWeight: '700' },
  boasVindasTexto: { color: cores.mutado, fontSize: 17, lineHeight: 25, marginTop: 14, marginBottom: 20 },
  avisoClinico: { backgroundColor: cores.verdeClaro, borderRadius: raios.grande, padding: espacamentos.md, marginVertical: espacamentos.md, borderLeftWidth: 3, borderLeftColor: cores.verde },
});
